=== JavierVelaR/Publico/PaginaFinal/Info.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="info">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="autor"/>
                <xs:element ref="titulo"/>
                <xs:choice maxOccurs="unbounded">
                    <xs:element ref="descripcion"/>
                    <xs:element ref="pagina"/>
                </xs:choice>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="autor" type="xs:string"/>
    <xs:element name="titulo" type="xs:string"/>
    <xs:element name="descripcion" type="xs:string"/>
    <xs:element name="pagina" type="xs:string"/>
</xs:schema>

=== JavierVelaR/Publico/PaginaFinal/Info.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="./Info.xsl"?>
<info xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./Info.xsd">
	
	<autor>Javier Vela Rivera</autor>
	<titulo>Trabajo Final 3er trimestre</titulo>
	<descripcion>Página Web hecha para el trabajo final de 1º DAM.</descripcion>
	
	<pagina>Inicio:</pagina>
	<descripcion>Página con imágenes clickables para ir a las páginas de hombre, mujer y niños; y un menú con la página de Info, el modal y la configuración.</descripcion>

	<pagina>Hombre, Mujer y Niños</pagina>
	<descripcion>Página que muestra ropa para hombres, mujeres y niños. Con menú navegable entre ellos, el inicio, y las páginas info y configuración, además del modal.</descripcion>
	
	<pagina>Info:</pagina>
	<descripcion>Página de información sobre la página web.</descripcion>
	
	<pagina>Modal:</pagina>
	<descripcion>Está integrado en cada página, explica los requisitos no obvios que se cumplen.</descripcion>
	
	<pagina>Configuración:</pagina>
	<descripcion>Página con los ajustes de la página, que se guardan al recargar la página.</descripcion>
	
</info>
